[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]

[language-server.typescript-language-server]
command = "bun"
args = ["--bun", "run", "typescript-language-server", "--stdio"]
